dictionaries = [
  "fr",
  "en_us",
]

include_paths = [
  "**/*.md",
  "**/*.txt",
]

words = [
  "codeberg",
  "cron",
  "homebrew",
  "hytale",
  "keymaps",
  "podman",
  "shellcheck",
  "tmux",
  "ufw",
  "vimrc",
]
