dictionaries = [
  "fr",
  "en_us",
]

include_paths = [
  "**/*.md",
  "**/*.txt",
]

words = [
  "Catppuccin",
  "codeberg",
  "cron",
  "flathub",
  "flatpak",
  "fzf",
  "homebrew",
  "hytale",
  "jerem",
  "jeremky",
  "keymaps",
  "podman",
  "shellcheck",
  "tmux",
  "ufw",
  "vimscript",
  "vimrc",
]
