# ─── hyprpaper.conf ──────────────────────────────────────────────────────

wallpaper {
    monitor  =
    path     = /home/jeremky/Images/Wallpapers/wave.jpeg
    fit_mode = cover
}

splash = false
