# ─── hyprtoolkit.conf ────────────────────────────────────────────────────

icon_theme = Papirus-Dark

background        = 0xff1e1e2e  # base       — fond principal
base              = 0xff313244  # surface0   — surfaces (champs, listes)
alternate_base    = 0xff45475a  # surface1   — lignes alternées / éléments secondaires
text              = 0xffcdd6f4  # text       — texte normal
bright_text       = 0xfff5e0dc  # rosewater  — texte accentué
accent            = 0xffcba6f7  # mauve      — accent principal
accent_secondary  = 0xff89b4fa  # blue       — accent secondaire
