dictionaries = [
    "fr",
    "en_us",
]
words = [
    "flathub",
    "jdocker",
    "jerem",
    "jeremky",
    "nginx",
    "podman",
    "shellcheck",
    "tmux",
    "ufw",
    "vimrc",
    "zoxide",
]

ignore_paths = [
  "**/*.cfg",
  "**/*.comp",
  "**/*.cron",
  "**/*.sh",
]
