dictionaries = [
  "fr",
  "en_us",
]
words = [
  "codeberg",
  "cron",
  "homebrew",
  "hytale",
  "jerem",
  "jeremky",
  "keymaps",
  "podman",
  "shellcheck",
  "tmux",
  "ufw",
  "vimrc",
]

ignore_paths = [
  "**/*.bashrc"
  "**/*.cfg",
  "**/*.comp",
  "**/*.cron",
  "**/*.sh",
]
