theme = "catppuccin_mocha"

[editor]
default-yank-register = "+"
cursorline = true
true-color = true
color-modes = true
scrolloff = 8
bufferline = "multiple"
idle-timeout = 400

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.file-picker]
hidden = false

[editor.lsp]
enable = false

[keys.normal]
"del" = "delete_char_forward"
"D" = ["select_mode", "goto_line_end", "delete_selection"]
"G" = "goto_last_line"
"$" = "goto_line_end"
"0" = "goto_line_start"

"F2" = ":toggle mouse"
"F4" = "toggle_comments"
"F5" = ":format"
