" ─── vimrc ───────────────────────────────────────────────────────────────

" Compatibility & syntax
set nocompatible                " Disable Vi compatibility
syntax on                       " Enable syntax highlighting
set ttimeout                    " Time out on key codes
set ttimeoutlen=50              " Esc has no noticeable delay

" Indentation & tabs
set autoindent                  " Keep indentation on a new line
set smarttab                    " Handle leading whitespace
set tabstop=2                   " Tab width is set to 2
set shiftwidth=2                " Indents are 2 wide
set softtabstop=2               " Number of columns for a tab
set expandtab                   " Replace tabs with spaces
set linebreak                   " Wrap lines without breaking words
set breakindent                 " Wrapped lines keep their indentation

" Search
set hlsearch                    " Highlight search results
set incsearch                   " Incremental search
set ignorecase                  " Ignore case
set smartcase                   " Smart case matching

" Interface & display
set background=dark             " Optimize display for a dark terminal
set ruler                       " Show cursor position
set showcmd                     " Show command in status line
set showmatch                   " Show matching brackets
set wildmenu                    " Command-line completion menu

" Windows, buffers & navigation
set hidden                      " Hide buffers when abandoned
set scrolloff=8                 " Keep 8 lines of context around the cursor
set splitbelow                  " Open horizontal splits below
set splitright                  " Open vertical splits to the right

" Miscellaneous behavior
set mouse=                      " Disable mouse by default
set nobackup                    " Disable automatic backups
set noswapfile                  " Disable swap files
set spelllang=en,fr             " Spell checking

" Enable automatic indentation: gg=G
filetype plugin indent on

" Invisible characters definition
let &listchars = "eol:$,space:\u00B7,tab:\u25B8\ ,trail:\u00B7"

" Change cursor shape based on mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
let &t_SR = "\e[4 q"
let &t_te .= "\e[0 q"

" Vertical popup completion menu
if has('patch-8.2.4325') | set wildoptions=pum | endif

" ─── functions ───────────────────────────────────────────────────────────

" Toggle line numbers and mouse
function! ModeIDE()
  let g:modeIDE_enabled = !get(g:, 'modeIDE_enabled', 0)
  let &mouse = g:modeIDE_enabled ? 'a' : ''
  let l:win = win_getid()
  windo let &l:number = g:modeIDE_enabled
  call win_gotoid(l:win)
  echo 'IDE mode ' . (g:modeIDE_enabled ? 'enabled' : 'disabled')
endfunction

" Reindent without moving the cursor
function! ReindentFile()
  let l:view = winsaveview()
  normal! gg=G
  call winrestview(l:view)
endfunction

" ─── mapping ─────────────────────────────────────────────────────────────

" Spell checker
nnoremap <F1> <Cmd>set spell!<CR>

" IDE mode
nnoremap <F2> <Cmd>call ModeIDE()<CR>

" Show invisible characters
nnoremap <F3> <Cmd>set list!<CR>

" Comment
nmap <F4> gcc
xmap <F4> gc

" Automatic indentation
nnoremap <F5> <Cmd>call ReindentFile()<CR>

" Clean plugins
nnoremap <F7> <Cmd>PlugClean<CR>

" Update plugins
nnoremap <F8> <Cmd>PlugUpdate<CR>

" Switch document
nnoremap <S-TAB> <C-w>w

" Clear search highlighting
nnoremap <silent> <CR> <Cmd>nohlsearch<CR><CR>

" ─── plugins ─────────────────────────────────────────────────────────────

" Download vim-plug if missing
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall automatically
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
      \| PlugInstall --sync | source $MYVIMRC
      \| endif

" Plugin list
call plug#begin('~/.vim/plugged')

Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'itchyny/lightline.vim'
Plug 'vim-scripts/VimCompletesMe'

" Comments (built-in comment plugin on Vim 9.1+)
try | packadd! comment | catch | Plug 'tpope/vim-commentary' | endtry

call plug#end()

" ─── autocmds ────────────────────────────────────────────────────────────

augroup vimrc
  autocmd!

  " Remember last cursor position
  autocmd BufReadPost *
        \ if (line("'\"") > 1) && (line("'\"") <= line("$"))
        \ |   silent exe "silent! normal g'\"zO"
        \ | endif

  " Disable comment continuation on newline
  autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

augroup END

" ─── plugins config ──────────────────────────────────────────────────────

if isdirectory(expand("~/.vim/plugged"))

  " Catppuccin
  silent! colorscheme catppuccin_mocha
  set cursorline
  set termguicolors

  " LightLine
  let g:lightline = {'colorscheme': 'catppuccin_mocha'}
  let g:lightline.separator = { 'left': '', 'right': '' }
  set laststatus=2
  set noshowmode

endif
